"""quick_replies_and_customer_lang

Revision ID: abd71af0a741
Revises: c2aa8796a530
Create Date: 2026-05-15 22:47:17.888705

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd71af0a741'
down_revision = 'c2aa8796a530'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('actor_kind', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_replies_actor_id'), 'quick_replies', ['actor_id'], unique=False)
    op.create_index(op.f('ix_quick_replies_actor_kind'), 'quick_replies', ['actor_kind'], unique=False)
    op.create_index(op.f('ix_quick_replies_category'), 'quick_replies', ['category'], unique=False)
    op.create_index(op.f('ix_quick_replies_is_public'), 'quick_replies', ['is_public'], unique=False)
    op.create_index(op.f('ix_quick_replies_merchant_id'), 'quick_replies', ['merchant_id'], unique=False)
    op.add_column('customers', sa.Column('last_source_lang', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'last_source_lang')
    op.drop_index(op.f('ix_quick_replies_merchant_id'), table_name='quick_replies')
    op.drop_index(op.f('ix_quick_replies_is_public'), table_name='quick_replies')
    op.drop_index(op.f('ix_quick_replies_category'), table_name='quick_replies')
    op.drop_index(op.f('ix_quick_replies_actor_kind'), table_name='quick_replies')
    op.drop_index(op.f('ix_quick_replies_actor_id'), table_name='quick_replies')
    op.drop_table('quick_replies')
    # ### end Alembic commands ###
