"""baseline

Revision ID: 09fde8b7adc6
Revises: 
Create Date: 2026-05-15 18:30:22.265683

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fde8b7adc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=120), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('actor_kind', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_kind'), 'audit_logs', ['actor_kind'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_username'), 'audit_logs', ['actor_username'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('business_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('platform_name', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('custom_image_url', sa.String(length=500), nullable=True),
    sa.Column('domains', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('online_status', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_agents_name'), 'business_agents', ['name'], unique=True)
    op.create_index(op.f('ix_business_agents_status'), 'business_agents', ['status'], unique=False)
    op.create_table('proxy_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_groups_name'), 'proxy_groups', ['name'], unique=True)
    op.create_table('support_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('online_status', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_agents_role'), 'support_agents', ['role'], unique=False)
    op.create_index(op.f('ix_support_agents_username'), 'support_agents', ['username'], unique=True)
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_agent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('online_status', sa.String(length=32), nullable=False),
    sa.Column('statistic_time', sa.String(length=8), nullable=True),
    sa.Column('last_login_at', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('ports_total', sa.Integer(), nullable=False),
    sa.Column('ports_used', sa.Integer(), nullable=False),
    sa.Column('ports_expires_at', sa.String(length=64), nullable=True),
    sa.Column('ports_reset_cycle_hours', sa.Integer(), nullable=False),
    sa.Column('ports_reset_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_agent_id'], ['business_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_business_agent_id'), 'merchants', ['business_agent_id'], unique=False)
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=True)
    op.create_index(op.f('ix_merchants_status'), 'merchants', ['status'], unique=False)
    op.create_table('proxy_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('max_accounts', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['proxy_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_endpoints_group_id'), 'proxy_endpoints', ['group_id'], unique=False)
    op.create_index(op.f('ix_proxy_endpoints_name'), 'proxy_endpoints', ['name'], unique=False)
    op.create_index(op.f('ix_proxy_endpoints_status'), 'proxy_endpoints', ['status'], unique=False)
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('sent_today', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_account_groups_merchant_id'), 'account_groups', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_account_groups_name'), 'account_groups', ['name'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('session_path', sa.String(length=500), nullable=False),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('sent_today', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_replies', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('avatar_status', sa.String(length=32), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_avatar_status'), 'accounts', ['avatar_status'], unique=False)
    op.create_index(op.f('ix_accounts_country'), 'accounts', ['country'], unique=False)
    op.create_index(op.f('ix_accounts_merchant_id'), 'accounts', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_accounts_nickname'), 'accounts', ['nickname'], unique=False)
    op.create_index(op.f('ix_accounts_phone'), 'accounts', ['phone'], unique=False)
    op.create_index(op.f('ix_accounts_proxy_id'), 'accounts', ['proxy_id'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_tg_user_id'), 'accounts', ['tg_user_id'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('task_kind', sa.String(length=32), nullable=False),
    sa.Column('operation_target', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('account_group_ids', sa.JSON(), nullable=True),
    sa.Column('customer_group_id', sa.Integer(), nullable=True),
    sa.Column('friend_filter', sa.JSON(), nullable=True),
    sa.Column('send_settings', sa.JSON(), nullable=True),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('queued_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('read_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.String(length=64), nullable=True),
    sa.Column('paused_at', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_customer_group_id'), 'campaigns', ['customer_group_id'], unique=False)
    op.create_index(op.f('ix_campaigns_merchant_id'), 'campaigns', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_task_kind'), 'campaigns', ['task_kind'], unique=False)
    op.create_index(op.f('ix_campaigns_template_id'), 'campaigns', ['template_id'], unique=False)
    op.create_table('material_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_groups_kind'), 'material_groups', ['kind'], unique=False)
    op.create_index(op.f('ix_material_groups_merchant_id'), 'material_groups', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_material_groups_name'), 'material_groups', ['name'], unique=False)
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_merchant_id'), 'message_templates', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_message_templates_name'), 'message_templates', ['name'], unique=False)
    op.create_table('phone_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_groups_country'), 'phone_groups', ['country'], unique=False)
    op.create_index(op.f('ix_phone_groups_merchant_id'), 'phone_groups', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_phone_groups_name'), 'phone_groups', ['name'], unique=False)
    op.create_table('account_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'group_id', name='uq_account_group_member')
    )
    op.create_index(op.f('ix_account_group_members_account_id'), 'account_group_members', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_group_members_group_id'), 'account_group_members', ['group_id'], unique=False)
    op.create_table('account_proxy_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('old_proxy_id', sa.Integer(), nullable=True),
    sa.Column('new_proxy_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['new_proxy_id'], ['proxy_endpoints.id'], ),
    sa.ForeignKeyConstraint(['old_proxy_id'], ['proxy_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_proxy_logs_account_id'), 'account_proxy_logs', ['account_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('assigned_account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_message_at', sa.String(length=64), nullable=True),
    sa.Column('last_read_at', sa.String(length=64), nullable=True),
    sa.Column('last_reply_at', sa.String(length=64), nullable=True),
    sa.Column('last_reply_text', sa.Text(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_assigned_account_id'), 'customers', ['assigned_account_id'], unique=False)
    op.create_index(op.f('ix_customers_consent'), 'customers', ['consent'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_group_id', sa.Integer(), nullable=True),
    sa.Column('tg_user_id', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_message_at', sa.String(length=64), nullable=True),
    sa.Column('last_read_at', sa.String(length=64), nullable=True),
    sa.Column('last_reply_at', sa.String(length=64), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_group_id'], ['account_groups.id'], ),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friends_account_group_id'), 'friends', ['account_group_id'], unique=False)
    op.create_index(op.f('ix_friends_account_id'), 'friends', ['account_id'], unique=False)
    op.create_index(op.f('ix_friends_phone'), 'friends', ['phone'], unique=False)
    op.create_index(op.f('ix_friends_status'), 'friends', ['status'], unique=False)
    op.create_index(op.f('ix_friends_tg_user_id'), 'friends', ['tg_user_id'], unique=False)
    op.create_index(op.f('ix_friends_username'), 'friends', ['username'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['material_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_group_id'), 'materials', ['group_id'], unique=False)
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('fmt', sa.String(length=40), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['phone_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phones_group_id'), 'phones', ['group_id'], unique=False)
    op.create_index(op.f('ix_phones_number'), 'phones', ['number'], unique=False)
    op.create_index(op.f('ix_phones_used'), 'phones', ['used'], unique=False)
    op.create_table('support_agent_group_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('account_group_id', sa.Integer(), nullable=False),
    sa.Column('can_view_friends', sa.Boolean(), nullable=False),
    sa.Column('can_view_chats', sa.Boolean(), nullable=False),
    sa.Column('can_send_message', sa.Boolean(), nullable=False),
    sa.Column('can_broadcast', sa.Boolean(), nullable=False),
    sa.Column('can_edit_profile', sa.Boolean(), nullable=False),
    sa.Column('can_delete_friend', sa.Boolean(), nullable=False),
    sa.Column('can_clear_chat', sa.Boolean(), nullable=False),
    sa.Column('can_export_data', sa.Boolean(), nullable=False),
    sa.Column('chat_scope', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_group_id'], ['account_groups.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['support_agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'account_group_id', name='uq_agent_account_group')
    )
    op.create_index(op.f('ix_support_agent_group_permissions_account_group_id'), 'support_agent_group_permissions', ['account_group_id'], unique=False)
    op.create_index(op.f('ix_support_agent_group_permissions_agent_id'), 'support_agent_group_permissions', ['agent_id'], unique=False)
    op.create_table('message_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('body_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.String(length=64), nullable=True),
    sa.Column('read_at', sa.String(length=64), nullable=True),
    sa.Column('replied_at', sa.String(length=64), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.String(length=64), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('locked_at', sa.String(length=64), nullable=True),
    sa.Column('external_message_id', sa.String(length=64), nullable=True),
    sa.Column('target_tg_user_id', sa.String(length=64), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_records_account_id'), 'message_records', ['account_id'], unique=False)
    op.create_index(op.f('ix_message_records_campaign_id'), 'message_records', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_message_records_customer_id'), 'message_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_message_records_external_message_id'), 'message_records', ['external_message_id'], unique=False)
    op.create_index(op.f('ix_message_records_friend_id'), 'message_records', ['friend_id'], unique=False)
    op.create_index(op.f('ix_message_records_next_run_at'), 'message_records', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_message_records_phone'), 'message_records', ['phone'], unique=False)
    op.create_index(op.f('ix_message_records_status'), 'message_records', ['status'], unique=False)
    op.create_index(op.f('ix_message_records_target_tg_user_id'), 'message_records', ['target_tg_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_records_target_tg_user_id'), table_name='message_records')
    op.drop_index(op.f('ix_message_records_status'), table_name='message_records')
    op.drop_index(op.f('ix_message_records_phone'), table_name='message_records')
    op.drop_index(op.f('ix_message_records_next_run_at'), table_name='message_records')
    op.drop_index(op.f('ix_message_records_friend_id'), table_name='message_records')
    op.drop_index(op.f('ix_message_records_external_message_id'), table_name='message_records')
    op.drop_index(op.f('ix_message_records_customer_id'), table_name='message_records')
    op.drop_index(op.f('ix_message_records_campaign_id'), table_name='message_records')
    op.drop_index(op.f('ix_message_records_account_id'), table_name='message_records')
    op.drop_table('message_records')
    op.drop_index(op.f('ix_support_agent_group_permissions_agent_id'), table_name='support_agent_group_permissions')
    op.drop_index(op.f('ix_support_agent_group_permissions_account_group_id'), table_name='support_agent_group_permissions')
    op.drop_table('support_agent_group_permissions')
    op.drop_index(op.f('ix_phones_used'), table_name='phones')
    op.drop_index(op.f('ix_phones_number'), table_name='phones')
    op.drop_index(op.f('ix_phones_group_id'), table_name='phones')
    op.drop_table('phones')
    op.drop_index(op.f('ix_materials_group_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_friends_username'), table_name='friends')
    op.drop_index(op.f('ix_friends_tg_user_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_status'), table_name='friends')
    op.drop_index(op.f('ix_friends_phone'), table_name='friends')
    op.drop_index(op.f('ix_friends_account_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_account_group_id'), table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_consent'), table_name='customers')
    op.drop_index(op.f('ix_customers_assigned_account_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_account_proxy_logs_account_id'), table_name='account_proxy_logs')
    op.drop_table('account_proxy_logs')
    op.drop_index(op.f('ix_account_group_members_group_id'), table_name='account_group_members')
    op.drop_index(op.f('ix_account_group_members_account_id'), table_name='account_group_members')
    op.drop_table('account_group_members')
    op.drop_index(op.f('ix_phone_groups_name'), table_name='phone_groups')
    op.drop_index(op.f('ix_phone_groups_merchant_id'), table_name='phone_groups')
    op.drop_index(op.f('ix_phone_groups_country'), table_name='phone_groups')
    op.drop_table('phone_groups')
    op.drop_index(op.f('ix_message_templates_name'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_merchant_id'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_material_groups_name'), table_name='material_groups')
    op.drop_index(op.f('ix_material_groups_merchant_id'), table_name='material_groups')
    op.drop_index(op.f('ix_material_groups_kind'), table_name='material_groups')
    op.drop_table('material_groups')
    op.drop_index(op.f('ix_campaigns_template_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_task_kind'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_merchant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_customer_group_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_accounts_tg_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_proxy_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_phone'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_nickname'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_merchant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_country'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_avatar_status'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_account_groups_name'), table_name='account_groups')
    op.drop_index(op.f('ix_account_groups_merchant_id'), table_name='account_groups')
    op.drop_table('account_groups')
    op.drop_index(op.f('ix_proxy_endpoints_status'), table_name='proxy_endpoints')
    op.drop_index(op.f('ix_proxy_endpoints_name'), table_name='proxy_endpoints')
    op.drop_index(op.f('ix_proxy_endpoints_group_id'), table_name='proxy_endpoints')
    op.drop_table('proxy_endpoints')
    op.drop_index(op.f('ix_merchants_status'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_business_agent_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_support_agents_username'), table_name='support_agents')
    op.drop_index(op.f('ix_support_agents_role'), table_name='support_agents')
    op.drop_table('support_agents')
    op.drop_index(op.f('ix_proxy_groups_name'), table_name='proxy_groups')
    op.drop_table('proxy_groups')
    op.drop_index(op.f('ix_business_agents_status'), table_name='business_agents')
    op.drop_index(op.f('ix_business_agents_name'), table_name='business_agents')
    op.drop_table('business_agents')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_kind'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
