"""message_translation_column

Revision ID: 49a1aa95b33a
Revises: abd71af0a741
Create Date: 2026-05-15 23:00:20.825523

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a1aa95b33a'
down_revision = 'abd71af0a741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_records', sa.Column('translation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_records', 'translation')
    # ### end Alembic commands ###
